In [1]:
import numpy as np
import pandas as pd

#### Loading the CSV file

In [2]:
df = pd.read_csv("../Telecaller/data/bank.csv")

In [3]:
print("Dataset Shape:", df.shape)
print("\nFirst 5 Rows:")
display(df.head())

Dataset Shape: (11162, 17)

First 5 Rows:

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [4]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='str')

In [5]:
print("\nData Types:")
print(df.dtypes)

Data Types:
age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome       str
deposit        str
dtype: object

#### Checking missing values

In [6]:
missing_values = df.isnull().sum()

missing_report = pd.DataFrame({
    "Missing_Count": missing_values,
    "Missing_Percentage": (missing_values / len(df)) * 100
})

display(missing_report)

           Missing_Count  Missing_Percentage
age                    0                 0.0
job                    0                 0.0
marital                0                 0.0
education              0                 0.0
default                0                 0.0
balance                0                 0.0
housing                0                 0.0
loan                   0                 0.0
contact                0                 0.0
day                    0                 0.0
month                  0                 0.0
duration               0                 0.0
campaign               0                 0.0
pdays                  0                 0.0
previous               0                 0.0
poutcome               0                 0.0
deposit                0                 0.0

#### Checking duplicate records

In [7]:
print("Total Duplicate Rows:", df.duplicated().sum())

Total Duplicate Rows: 0

#### Checking categorical values

In [8]:
categorical_cols = df.select_dtypes(
    include="object"
).columns

for col in categorical_cols:
    print("\n")
    print(df[col].value_counts(dropna=False))

job
management       2566
blue-collar      1944
technician       1823
admin.           1334
services          923
retired           778
self-employed     405
student           360
unemployed        357
entrepreneur      328
housemaid         274
unknown            70
Name: count, dtype: int64


marital
married     6351
single      3518
divorced    1293
Name: count, dtype: int64


education
secondary    5476
tertiary     3689
primary      1500
unknown       497
Name: count, dtype: int64


default
no     10994
yes      168
Name: count, dtype: int64


housing
no     5881
yes    5281
Name: count, dtype: int64


loan
no     9702
yes    1460
Name: count, dtype: int64


contact
cellular     8042
unknown      2346
telephone     774
Name: count, dtype: int64


month
may    2824
aug    1519
jul    1514
jun    1222
nov     943
apr     923
feb     776
oct     392
jan     344
sep     319
mar     276
dec     110
Name: count, dtype: int64


poutcome
unknown    8326
failure    1228
success    1071
other       537
Name: count, dtype: int64


deposit
no     5873
yes    5289
Name: count, dtype: int64

C:\Users\harsh\AppData\Local\Temp\ipykernel_6036\3156359178.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(

#### Checking numerical values

In [9]:
numerical_cols = df.select_dtypes(
    include="number"
).columns

display(df[numerical_cols].describe().T)

,count,mean,std,min,25%,50%,75%,max
age,11162.0,41.231948,11.913369,18.0,32.0,39.0,49.00,95.0
balance,11162.0,1528.538524,3225.413326,-6847.0,122.0,550.0,1708.00,81204.0
day,11162.0,15.658036,8.420740,1.0,8.0,15.0,22.00,31.0
duration,11162.0,371.993818,347.128386,2.0,138.0,255.0,496.00,3881.0
campaign,11162.0,2.508421,2.722077,1.0,1.0,2.0,3.00,63.0
pdays,11162.0,51.330407,108.758282,-1.0,-1.0,-1.0,20.75,854.0
previous,11162.0,0.832557,2.292007,0.0,0.0,0.0,1.00,58.0

#### Validating numerical columns

In [10]:
print("Age below 18:", (df["age"] < 18).sum())
print("Age above 100:", (df["age"] > 100).sum())

Age below 18: 0
Age above 100: 0

#### Checking account balance

In [11]:
print("Negative balances:", (df["balance"] < 0).sum())
print("Zero balances:", (df["balance"] == 0).sum())
print("Positive balances:", (df["balance"] > 0).sum())

Negative balances: 688
Zero balances: 774
Positive balances: 9700

#### Checking campaign contacts

In [12]:
print("Campaign below 1:", (df["campaign"] < 1).sum())
print("Campaign above 10:", (df["campaign"] > 10).sum())

print(
    df.loc[df["campaign"] > 10,
           ["age", "job", "campaign", "deposit"]]
      .sort_values("campaign", ascending=False)
      .head(10)
)

Campaign below 1: 0
Campaign above 10: 210
       age            job  campaign deposit
7635    45     management        63      no
6927    51    blue-collar        43      no
7240    33    blue-collar        43      no
7139    42    blue-collar        41      no
9683    49       services        33      no
7237    42  self-employed        32      no
4912    50   entrepreneur        32     yes
10293   31       services        31      no
10865   51       services        30      no
7763    44       services        30      no

#### Understanding pdays

In [13]:
print(df["pdays"].value_counts().head(10))

print("Never previously contacted:", (df["pdays"] == -1).sum())
print("Previously contacted:", (df["pdays"] != -1).sum())

pdays
-1      8324
 92      106
 182      89
 91       84
 181      81
 183      73
 184      52
 94       42
 93       41
 95       39
Name: count, dtype: int64
Never previously contacted: 8324
Previously contacted: 2838

##### In this dataset, pdays = -1 means the customer was not previously contacted in an earlier campaign. 
##### It is a special code, not an ordinary negative number.

#### Creating useful derived columns

#### Customer age group

In [14]:

df["age_group"] = pd.cut(
    df["age"],
    bins=[17, 25, 35, 45, 55, 65, float("inf")],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "66+"
    ]
)

print(df[["age", "age_group"]].head(10))

   age age_group
0   59     56-65
1   56     56-65
2   41     36-45
3   55     46-55
4   54     46-55
5   42     36-45
6   56     56-65
7   60     56-65
8   37     36-45
9   28     26-35

#### Previous contact status

In [15]:
df["previously_contacted"] = df["pdays"].apply(
    lambda x: "No" if x == -1 else "Yes"
)

print(df["previously_contacted"].value_counts())

previously_contacted
No     8324
Yes    2838
Name: count, dtype: int64

#### Balance category

In [16]:
df["balance_category"] = np.select(
    [
        df["balance"] < 0,
        df["balance"] == 0,
        df["balance"] <= 1000,
        df["balance"] <= 5000
    ],
    [
        "Negative",
        "Zero",
        "Low",
        "Medium"
    ],
    default="High"
)

print(df["balance_category"].value_counts())

balance_category
Low         5659
Medium      3270
Zero         774
High         771
Negative     688
Name: count, dtype: int64

#### Campaign contact group

In [17]:
df["campaign_group"] = pd.cut(
    df["campaign"],
    bins=[0, 1, 3, 5, float("inf")],
    labels=[
        "1 Contact",
        "2-3 Contacts",
        "4-5 Contacts",
        "6+ Contacts"
    ]
)

print(df["campaign_group"].value_counts())

campaign_group
1 Contact       4798
2-3 Contacts    4349
4-5 Contacts    1149
6+ Contacts      866
Name: count, dtype: int64

In [18]:
print("Totoal Rows and columns :",df.shape)
print("Columns Name :",df.columns)

Totoal Rows and columns : (11162, 21)
Columns Name : Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit', 'age_group', 'previously_contacted',
       'balance_category', 'campaign_group'],
      dtype='str')

#### EDA

##### Customers quantity in each deposit category and percentage distribution

In [19]:
deposit_summary = pd.DataFrame({
    "Customer_Count": df["deposit"].value_counts(),
    "Percentage": (
        df["deposit"].value_counts(normalize=True) * 100
    ).round(2)
})

deposit_summary.index.name = "Deposit_Status"

print(deposit_summary)

                Customer_Count  Percentage
Deposit_Status
no                        5873       52.62
yes                       5289       47.38

#### Creating a KPI variable

In [20]:
total_customers = len(df)

subscribed_customers = (df["deposit"] == "yes").sum()

subscription_rate = (
    subscribed_customers / total_customers
) * 100

print("Total Customers:", total_customers)
print("Subscribed Customers:", subscribed_customers)
print("Subscription Rate:", round(subscription_rate, 2), "%")

Total Customers: 11162
Subscribed Customers: 5289
Subscription Rate: 47.38 %

##### Approximately 47 out of every 100 customers subscribed to a term deposit in this dataset. The remaining 53 did not.

#### Which customer groups have higher term-deposit subscription rates?

In [21]:
job_analysis = df.groupby("job", observed=True).agg(
    Total_Customers=("deposit", "count"),
    Subscribed=("deposit", lambda x: (x == "yes").sum())
)

job_analysis["Subscription_Rate"] = (
    job_analysis["Subscribed"]
    / job_analysis["Total_Customers"]
    * 100
).round(2)

job_analysis = job_analysis.sort_values(
    "Subscription_Rate",
    ascending=False
)

print(job_analysis)

               Total_Customers  Subscribed  Subscription_Rate
job
student                    360         269              74.72
retired                    778         516              66.32
unemployed                 357         202              56.58
management                2566        1301              50.70
unknown                     70          34              48.57
admin.                    1334         631              47.30
self-employed              405         187              46.17
technician                1823         840              46.08
services                   923         369              39.98
housemaid                  274         109              39.78
entrepreneur               328         123              37.50
blue-collar               1944         708              36.42

#### Analyzing subscription by marital status

In [22]:
marital_analysis = df.groupby("marital", observed=True).agg(
    Total_Customers=("deposit", "count"),
    Subscribed=("deposit", lambda x: (x == "yes").sum())
)

marital_analysis["Subscription_Rate"] = (
    marital_analysis["Subscribed"]
    / marital_analysis["Total_Customers"]
    * 100
).round(2)

print(
    marital_analysis.sort_values(
        "Subscription_Rate",
        ascending=False
    )
)

          Total_Customers  Subscribed  Subscription_Rate
marital
single               3518        1912              54.35
divorced             1293         622              48.11
married              6351        2755              43.38

#### Analyzing subscription by education

In [23]:
education_analysis = df.groupby("education", observed=True).agg(
    Total_Customers=("deposit", "count"),
    Subscribed=("deposit", lambda x: (x == "yes").sum())
)

education_analysis["Subscription_Rate"] = (
    education_analysis["Subscribed"]
    / education_analysis["Total_Customers"]
    * 100
).round(2)

print(
    education_analysis.sort_values(
        "Subscription_Rate",
        ascending=False
    )
)

           Total_Customers  Subscribed  Subscription_Rate
education
tertiary              3689        1996              54.11
unknown                497         252              50.70
secondary             5476        2450              44.74
primary               1500         591              39.40

#### Analyzing subscription by contact type

In [24]:
contact_analysis = df.groupby("contact", observed=True).agg(
    Total_Customers=("deposit", "count"),
    Subscribed=("deposit", lambda x: (x == "yes").sum())
)

contact_analysis["Subscription_Rate"] = (
    contact_analysis["Subscribed"]
    / contact_analysis["Total_Customers"]
    * 100
).round(2)

print(
    contact_analysis.sort_values(
        "Subscription_Rate",
        ascending=False
    )
)

           Total_Customers  Subscribed  Subscription_Rate
contact
cellular              8042        4369              54.33
telephone              774         390              50.39
unknown               2346         530              22.59

#### Python to Sql Data Pipeline

In [25]:
from sqlalchemy import create_engine

username = "root"
password = "12345"
host = "localhost"
port = "3306"
database = "bank_db"

engin = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

table_name = "bank"

df.to_sql(
    table_name,
    engin,
    if_exists="replace",
    index=False
)

sql_data = pd.read_sql(f"Select * from {table_name} limit 5",engin)
sql_data.head(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,...,duration,campaign,pdays,previous,poutcome,deposit,age_group,previously_contacted,balance_category,campaign_group
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,...,1042,1,-1,0,unknown,yes,56-65,No,Medium,1 Contact
1,56,admin.,married,secondary,no,45,no,no,unknown,5,...,1467,1,-1,0,unknown,yes,56-65,No,Low,1 Contact
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,...,1389,1,-1,0,unknown,yes,36-45,No,Medium,1 Contact
3,55,services,married,secondary,no,2476,yes,no,unknown,5,...,579,1,-1,0,unknown,yes,46-55,No,Medium,1 Contact
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,...,673,2,-1,0,unknown,yes,46-55,No,Low,2-3 Contacts